/* nametable.h - GENERATED by scripts/gen_nametable.py. Do not edit. */
#ifndef NAMETABLE_H
#define NAMETABLE_H
#include <stddef.h>
#include <string.h>
typedef struct { const char *id; const char *name; } nt_entry_t;
static const nt_entry_t g_nametable[] = {
    { "APOL00004", "Apollo Save Tool" },
    { "CHTM00777", "PS4 Cheats Manager" },
    { "CUSA00001", "THE PLAYROOM" },
    { "CUSA00021", "WATCH_DOGS\342\204\242" },
    { "CUSA00127", "Netflix" },
    { "CUSA00135", "BATMAN\342\204\242: ARKHAM KNIGHT" },
    { "CUSA00219", "Destiny" },
    { "CUSA00411", "Grand Theft Auto V" },
    { "CUSA00568", "Destiny" },
    { "CUSA00572", "SHAREfactory\342\204\242" },
    { "CUSA00740", "Terraria" },
    { "CUSA00960", "PlayStation\342\204\242 Vue" },
    { "CUSA01000", "Destiny" },
    { "CUSA01004", "Sleeping Dogs" },
    { "CUSA01015", "YouTube" },
    { "CUSA01697", "PlayStation\342\204\242Now" },
    { "CUSA01780", "Spotify" },
    { "CUSA01839", "STREET FIGHTER IV" },
    { "CUSA02012", "Media Player" },
    { "CUSA03245", "Deadpool" },
    { "CUSA04294", "WATCH_DOGS\302\256 2" },
    { "CUSA04602", "Batman: Arkham City" },
    { "CUSA06014", "TEKKEN\342\204\2427" },
    { "CUSA06712", "Goat Simulator" },
    { "CUSA08992", "DRAGON BALL FighterZ" },
    { "CUSA11995", "Marvel's Spider-Man" },
    { "CUSA13323", "Ghost of Tsushima" },
    { "CUSA14909", "SpongeBob SquarePants: Battle For Bikini Bottom" },
    { "CUSA18795", "Skater XL" },
    { "CUSA20177", "Marvel's Spider-Man: Miles Morales" },
    { "CUSA20499", "Cuphead" },
    { "CUSA24899", "Stray" },
    { "CUSA26618", "Grand Theft Auto: San Andreas \342\200\223 The Definitive Edition" },
    { "FLTZ00003", "Remote PKG installer" },
    { "GBTX00001", "GameBaTo" },
    { "LAPY20006", "PS4 Temperature" },
    { "LAPY20009", "PS4-Xplorer 2.0" },
    { "LAPY20015", "Avatar Changer" },
    { "MANU90003", "FPKGi Data" },
    { "NPXS20102", "Internet Browser" },
    { "NPXS20104", "Capture Gallery" },
    { "NPXS20105", "Live from PlayStation" },
    { "NPXS20106", "Music Unlimited" },
    { "NPXS20107", "PlayStation\342\204\242Video - My Videos" },
    { "NPXS20108", "What's New" },
    { "NPXS20109", "\357\242\226" },
    { "NPXS20110", "TV & Video" },
    { "NPXS20111", "Library" },
    { "NPXS20112", "\357\242\226\357\242\226" },
    { "NPXS20114", "PlayStation\342\204\242Now" },
    { "NPXS20117", "USB Music Player" },
    { "NPXS20118", "Share Play" },
    { "NPXS20120", "PlayStation\342\204\242Video" },
    { "NPXS20132", "\357\242\226" },
    { "NPXS20133", "\357\242\226" },
    { "NPXS20979", "PlayStation Store" },
    { "NPXS21021", "PS5 Remote Play" },
    { "NPXS39041", "Store" },
    { "PKGI13337", "FPKGi" },
};
static const size_t g_nametable_count = sizeof g_nametable / sizeof g_nametable[0];
static int nametable_lookup(const char *tid, char *out, size_t cap){
    if(!tid || !out || cap == 0) return -1;
    for(size_t i = 0; i < g_nametable_count; i++){
        if(!strcmp(tid, g_nametable[i].id)){
            strncpy(out, g_nametable[i].name, cap - 1);
            out[cap - 1] = 0;
            return out[0] ? 0 : -1;
        }
    }
    return -1;
}
#endif
